version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: false

formats: 
  - pdf
  - epub

python:
  version: 3
  install:
    - requirements: docs/requirements.txt
  system_packages: true
